/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface LibkrunConfig {
  /** Number of virtual CPUs */
  cpus?: number
  /** Memory in MiB */
  memoryMib?: number
  /** Root filesystem path */
  rootfsPath: string
  /** Working directory inside VM */
  workdir?: string
  /** virtiofs mounts: { tag: host_path } */
  mounts?: Record<string, string>
  /** Port mappings: ["host:guest", ...] */
  portMap?: Array<string>
  /** Environment variables */
  env?: Record<string, string>
}
export interface VmInfo {
  ctxId: number
  cid: number
  cpus: number
  memoryMib: number
}
/** Check if libkrun is available on this system */
export declare function isAvailable(): boolean
/** Get libkrun version string */
export declare function getVersion(): string
/** Create a new libkrun VM context */
export declare function createContext(config: LibkrunConfig): VmInfo
/**
 * Start the VM (blocking - runs in the current thread)
 * Note: krun_start_enter blocks, so this needs special handling
 */
export declare function startVm(ctxId: number): number
/** Free a VM context */
export declare function freeContext(ctxId: number): void
/** Set the executable to run in the VM */
export declare function setExec(ctxId: number, execPath: string, args: Array<string>, env: Record<string, string>): void
